services:
  caddy:
    image: caddy:latest
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile:ro
    - caddy-config:/config
    - caddy-data:/data

volumes:
  caddy-config:
  caddy-data:

