version: '3'
services:
  php:
    build: .
    image: docbuc/php-fpm:alpine-exif
    volumes:
      - www:/var/www/html
      - vendor:/var/www/html/vendor
  nginx:
    image: nginx:1
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - www:/var/www/html
      - vendor:/var/www/html/vendor
    ports:
      - 8080:80
volumes:
  vendor:
  www:
