services:
  mongo1:
    image: mongo:5
    command: --replSet "rs0"
    volumes:
      - mongovol1:/data/db
  mongo2:
    image: mongo:5
    command: --replSet "rs0"
    volumes:
      - mongovol2:/data/db
  mongo3:
    image: mongo:5
    command: --replSet "rs0"
    volumes:
      - mongovol3:/data/db
  api:
    restart: always
    build: api
    image: docbuc/mwa-api
    environment:
      - MONGO_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      - HEALTH_URL=http://localhost:3000/health
    depends_on:
      - mongo1
    ports:
      - 3000:3000
  redis:
    image: redis:7-alpine
  frontend:
    restart: always
    build: frontend
    image: docbuc/mwa-fe
    depends_on:
      - api
    ports:
      - 80:8080
volumes:
  mongovol1:
  mongovol2:
  mongovol3:
